---
- name: Install Google Chrome on Linux (Clean + Multi-user safe)
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    # -------------------------------------------------
    # Debian / Ubuntu - Install Chrome
    # -------------------------------------------------

    - name: Install dependencies (Debian-based)
      apt:
        name:
          - wget
          - gnupg
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add Google Chrome GPG key (Debian-based)
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Google Chrome repository (Debian-based)
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Google Chrome (Debian-based)
      apt:
        name: google-chrome-stable
        state: present
      when: ansible_os_family == "Debian"

    # -------------------------------------------------
    # Cleanup duplicate Chrome sources
    # -------------------------------------------------

    - name: Remove snap chromium if present (prevents duplicate icons)
      command: snap remove chromium
      when: ansible_os_family == "Debian"
      ignore_errors: yes

    # -------------------------------------------------
    # Multi-user Chrome desktop cleanup
    # -------------------------------------------------

    - name: Find all Google Chrome desktop entries under /home
      find:
        paths: /home
        patterns: google-chrome.desktop
        recurse: yes
      register: chrome_desktop_files
      when: ansible_os_family == "Debian"

    - name: Remove duplicate Google Chrome desktop entries for all users
      file:
        path: "{{ item.path }}"
        state: absent
      lo

