---
- name: Enforce single Google Chrome installation (GNOME desktops)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    chrome_package: google-chrome-stable

  tasks:

  ####################################################################
  # PREFLIGHT (INFO ONLY)
  ####################################################################

    - name: Preflight | Show existing Chrome / Chromium packages
      shell: dpkg -l | egrep -i "chrome|chromium" || true
      register: preflight_packages
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Preflight report
      debug:
        msg: "{{ preflight_packages.stdout | default('No Chrome/Chromium packages detected') }}"
      when: ansible_os_family == "Debian"

  ####################################################################
  # REMOVE NON-APPROVED BROWSERS
  ####################################################################

    - name: Remove Chromium (APT)
      apt:
        name:
          - chromium
          - chromium-browser
        state: absent
        purge: yes
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Remove Chrome beta / unstable
      apt:
        name:
          - google-chrome-beta
          - google-chrome-unstable
        state: absent
        purge: yes
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Remove Chromium snap
      command: snap remove chromium
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Remove Chromium flatpak
      command: flatpak uninstall -y org.chromium.Chromium
      ignore_errors: yes
      when: ansible_os_family == "Debian"

  ####################################################################
  # PRE-INSTALL DESKTOP CLEANUP (DEFENSIVE)
  ####################################################################

    - name: Remove stale Chrome / Chromium desktop files (pre-install)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/share/applications/com.google.Chrome.desktop
        - /usr/share/applications/chromium.desktop
        - /usr/share/applications/chromium-browser.desktop
        - /var/lib/snapd/desktop/applications/chromium_chromium.desktop
        - /home/*/.local/share/applications/com.google.Chrome.desktop
      ignore_errors: yes
      when: ansible_os_family == "Debian"

  ####################################################################
  # INSTALL APPROVED GOOGLE CHROME
  ####################################################################

    - name: Add Google Chrome GPG key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Google Chrome repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Google Chrome (stable)
      apt:
        name: "{{ chrome_package }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

  ####################################################################
  # POST-INSTALL DESKTOP NORMALIZATION (CRITICAL FIX)
  ####################################################################

    - name: Remove duplicate Chrome desktop app created during install
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/share/applications/com.google.Chrome.desktop
        - /home/*/.local/share/applications/com.google.Chrome.desktop
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Rebuild desktop application database (post-install)
      command: update-desktop-database
      ignore_errors: yes
      when: ansible_os_family == "Debian"

  ####################################################################
  # GNOME FAVORITES NORMALIZATION (PER USER)
  ####################################################################

    - name: Fix GNOME favorites – enforce single Chrome icon
      become: false
      shell: |
        CURRENT=$(gsettings get org.gnome.shell favorite-apps)
        CLEANED=$(echo "$CURRENT" | sed "s/'com.google.Chrome.desktop', //; s/, 'com.google.Chrome.desktop'//; s/'com.google.Chrome.desktop'//")
        gsettings set org.gnome.shell favorite-apps "$CLEANED"
      environment:
        DISPLAY: ":0"
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_uid }}"
      when:
        - ansible_env.XDG_CURRENT_DESKTOP is defined
        - ansible_env.XDG_CURRENT_DESKTOP | regex_search("GNOME")
      ignore_errors: yes

